server:
  port: 8082

spring:
  h2:
    console:
      enabled: true
  application:
    name: PAYMENT-SERVICE
  zipkin:
    base-url: http://localhost:9411

logging:
  file: C:/Users/srini/Desktop/backup/logs/payment-service.log