server:
  port: 8081

spring:
  h2:
    console:
      enabled: true
  application:
    name: ORDER-SERVICE
  zipkin:
    base-url: http://localhost:9411/
logging:
  file: C:/Users/srini/Desktop/backup/logs/order-service.log
